export const pageComponents: Record<string, string[]> = {
    home: [
        "Hero",
        "InsightSection1",
        "InsightSection2",
        "RevenueLeakSection",
        "ApproachSection",
        "ProofSection",
        "SecurityComplianceSection",
        "PracticeFinderSection",
        "HomeContactSection",
        "FooterSection",
    ],
    about: ["Hero", "Mission", "Story", "Values", "Compliance", "FooterSection"],
    specialties: ["Hero", "Stats", "GroupBilling", "Walkthrough", "InstitutionalBilling", "LabSpecialties", "FooterSection"],
    services: ["Hero", "Scope", "Process", "FooterSection"],
    solutions: ["Hero", "Walkthrough", "PackagesSection", "FooterSection"],
    resources: ["Hero", "FeaturedVideos", "ResourcesTabs", "FooterSection"],
    careers: ["Hero", "WhyMeBilling", "Openings", "FooterSection"],
    contact: ["Hero", "HomeContactSection", "FooterSection"],
    sales: ["Hero", "SalesPillarsAccordion", "FooterSection"],
    "privacy-policy": ["Hero", "FooterSection"],
};
